package views.students;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.GregorianCalendar;
import models.Group;
import models.Student;
import models.Teacher;
import resources.Util;

/**
 *
 * @author Jhonathan Mejia Leon
 */
public class NewStudent extends javax.swing.JFrame {
  private javax.swing.JFrame parent;
  private Student student;
  
  /**
   * Creates new form ReporteEstudiantes
   */
  public NewStudent(javax.swing.JFrame parent, int studentRN) {
    this.parent = parent;
    this.student = Student.find(studentRN);
    initComponents();
    addAttributes();
    loadData();
    try {
      loadGroups();
    } catch(Exception e) {
      System.out.println(e.getMessage());
    }
  }
  
  private void addAttributes() {
    setLocationRelativeTo(null);
    setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    this.addWindowListener(new WindowListener() {
      @Override
      public void windowOpened(WindowEvent e) {
        parent.setEnabled(false);
      }

      @Override
      public void windowClosing(WindowEvent e) {
        parent.setEnabled(true);
      }

      @Override
      public void windowClosed(WindowEvent e) {}

      @Override
      public void windowIconified(WindowEvent e) {}

      @Override
      public void windowDeiconified(WindowEvent e) {}

      @Override
      public void windowActivated(WindowEvent e) {}

      @Override
      public void windowDeactivated(WindowEvent e) {}
    });
  }
  
  private void loadGroups() throws SQLException {
    Group.all().forEach(group -> {
      this.groupsCombo.addItem(String.format("%d- %s", group.getId(), group.getName()));
    });
  }
  
  private void loadData() {
    if (this.student == null) {
      this.incorporatioDateField.setText(now());
      return;
    }
    this.codeField.setText(String.valueOf(this.student.getCi()));
    this.namesField.setText(this.student.getName());
    this.lastNamesField.setText(this.student.getLastName());
    this.incorporatioDateField.setText(this.student.getIncorporationDate().toString());
  }

  private String now() {
    GregorianCalendar calendar = new GregorianCalendar();
    return String.format(
      "%d-%d-%d %d:%d:%d", 
      calendar.get(Calendar.YEAR), 
      calendar.get(Calendar.MONTH), 
      calendar.get(Calendar.MONTH),
      calendar.get(Calendar.HOUR_OF_DAY),
      calendar.get(Calendar.MINUTE),
      calendar.get(Calendar.SECOND)
    );
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel9 = new javax.swing.JPanel();
    namesField = new javax.swing.JTextField();
    lastNamesField = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    groupsCombo = new javax.swing.JComboBox();
    jButton2 = new javax.swing.JButton();
    jLabel6 = new javax.swing.JLabel();
    incorporatioDateField = new javax.swing.JTextField();
    codeField = new javax.swing.JFormattedTextField(new Integer(1600035));

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información Personal-Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 12), new java.awt.Color(0, 102, 255))); // NOI18N

    jLabel2.setText("Código:");

    jLabel3.setText("Nombres:");

    jLabel4.setText("Apellidos:");

    jLabel1.setText("Grupo de Investigación:");

    groupsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grupo de la base de datos" }));

    jButton2.setText("Añadir");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jLabel6.setText("Fecha de Ingreso:: AAAA-MM-DD HH:MM:SS");

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
      jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel9Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(namesField)
          .addComponent(lastNamesField)
          .addComponent(incorporatioDateField)
          .addComponent(groupsCombo, 0, 344, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jButton2))
          .addGroup(jPanel9Layout.createSequentialGroup()
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addComponent(jLabel6)
              .addComponent(jLabel3)
              .addComponent(jLabel2)
              .addComponent(jLabel4))
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(codeField))
        .addContainerGap())
    );
    jPanel9Layout.setVerticalGroup(
      jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel9Layout.createSequentialGroup()
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(4, 4, 4)
        .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(namesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(lastNamesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(incorporatioDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(8, 8, 8)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(groupsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jButton2)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int code = Integer.parseInt(this.codeField.getValue().toString());
    int groupId = 0;
    String name = this.namesField.getText();
    String lastName = this.lastNamesField.getText();
    String incorporationDate = this.incorporatioDateField.getText();
    
    if (!Util.hasText(this.codeField.getText()) 
        || !Util.hasText(name) 
        || !Util.hasText(lastName) 
        || !Util.hasText(incorporationDate)) {
      Util.showWarning(this, "Los datos no son válidos");
      return;
    }
    if (this.groupsCombo.getSelectedIndex() != 0)
      groupId = Util.getPKFromCombo(this.groupsCombo);
    
    Timestamp incorporationDateT = Timestamp.valueOf(incorporationDate);
    if (this.student == null) {
      this.student = new Student(code, name, lastName, incorporationDateT);
      if (groupId != 0) this.student.setGroupId(groupId);
      
      try {
        this.student.save();
        Util.showWarning(this, "Datos guardados");
        System.out.println(student);
      } catch(SQLException e) {
        Util.showWarning(this, e.getMessage());
      }
    } else {
      if (!this.student.getName().equals(name)) this.student.setName(name);
      if (!this.student.getLastName().equals(lastName)) this.student.setLastName(lastName);
      if (!this.student.getIncorporationDate().equals(incorporationDate)) this.student.setIncorporationDate(incorporationDateT);
      try {
        this.student.update();
        Util.showWarning(this, "Datos actualizados");
      } catch(SQLException e) {
        Util.showWarning(this, e.getMessage());
      }
    }
    dispose();
    parent.setEnabled(true);
  }//GEN-LAST:event_jButton2ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JFormattedTextField codeField;
  private javax.swing.JComboBox groupsCombo;
  private javax.swing.JTextField incorporatioDateField;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JTextField lastNamesField;
  private javax.swing.JTextField namesField;
  // End of variables declaration//GEN-END:variables
}
