package views.students;

import java.awt.Color;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import models.Project;
import models.Student;
import models.Teacher;
import models.Tribunal;

/**
 *
 * @author javier
 */
public class ShowStudent extends javax.swing.JFrame {
  private javax.swing.JFrame parent;
  private Student student;
  private Project project;
  private Tribunal tribunal;
  private Teacher teacher;
  /**
   * Creates new form ShowStudent
   */
  public ShowStudent(javax.swing.JFrame parent, Student student) {
    this.parent = parent;
    this.student = student;
    this.project = Project.find(student.getOrderNumber());
    if(project != null) this.tribunal = project.getTribunal();
    this.teacher = Teacher.find(student.getTeacherId());
    initComponents();
    addAttributes();
    
    try {
      loadStudentData();
      loadProjectData();
      loadTribunalData();
      loadTeacherData();
    } catch(Exception e) {
      
    }
  }
  
  private void loadStudentData() {
    this.studentNames.setText(this.student.getName() + " " + this.student.getLastName());
    this.studentCode.setText(this.student.getCi() + "");
  }
  
  private void loadProjectData() {
    if (this.project == null) {
      loadDefaultDataForProject();
      return;
    }
    //Project data
    this.projectTheme.setText("Tema: " + this.project.getTheme().getTitle());
    this.projectStartDate.setText("Fecha de inicio: " + this.project.getStartDate().toString());
    this.projectEndDate.setText("Fecha final: " + this.project.getEndDate() == null ? this.project.getDuration() : this.project.getEndDate().toString());
    this.projectDuration.setText("Duración: " + this.project.getDuration());
    this.projectState.setText("Estado: " + this.project.getStatus());
  }
  
  private void loadTeacherData() {
    if (this.teacher == null) {
      this.projectTeacherName.setText("");
      this.projectTeacherAddress.setText("");
      return;
    }
    this.projectTeacherName.setText(this.teacher.getFullName());
    this.projectTeacherAddress.setText(this.teacher.getAddress());
  }
  
  private void loadDefaultDataForProject() {
    this.projectTheme.setText("");
    this.projectStartDate.setText("El estudiante aún no ha creado un proyecto");
    this.projectEndDate.setText("");
    this.projectDuration.setText("");
    this.projectState.setText("");
    this.projectTeacherName.setText("");
    this.projectTeacherAddress.setText("");
    
    this.tribunalPresentationPlace.setText("");
    this.tribunalComponentsNumber.setText("");
    this.tribunalTeacherName.setText("");
    this.tribunalTeacherAddress.setText("");
  }
  
  private void loadTribunalData() {
    //Tribunal data
    if (tribunal == null) return;
    this.tribunalPresentationPlace.setText("Lugar de presentación: " + this.tribunal.getTestPlace());
    this.tribunalComponentsNumber.setText(String.format("%d integrantes", this.tribunal.getComponentsNumber()));
    this.tribunalTeacherName.setText(this.tribunal.getTitularTeacher().getFullName());
    this.tribunalTeacherAddress.setText(this.tribunal.getTitularTeacher().getAddress());
  }
  
  private void addAttributes() {
    setLocationRelativeTo(this.parent);
    setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    getContentPane().setBackground(Color.white);
    setTitle(this.student.getName());
    this.addWindowListener(new WindowListener() {
      @Override
      public void windowOpened(WindowEvent e) {
        parent.setEnabled(false);
      }

      @Override
      public void windowClosing(WindowEvent e) {
        parent.setEnabled(true);
      }

      @Override
      public void windowClosed(WindowEvent e) {}

      @Override
      public void windowIconified(WindowEvent e) {}

      @Override
      public void windowDeiconified(WindowEvent e) {}

      @Override
      public void windowActivated(WindowEvent e) {}

      @Override
      public void windowDeactivated(WindowEvent e) {}
    });
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel5 = new javax.swing.JPanel();
    projectTeacherAddress = new javax.swing.JLabel();
    projectTeacherName = new javax.swing.JLabel();
    jPanel9 = new javax.swing.JPanel();
    tribunalTeacherName = new javax.swing.JLabel();
    tribunalTeacherAddress = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    tribunalPresentationPlace = new javax.swing.JLabel();
    tribunalComponentsNumber = new javax.swing.JLabel();
    studentNames = new javax.swing.JLabel();
    studentCode = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    projectTheme = new javax.swing.JLabel();
    projectStartDate = new javax.swing.JLabel();
    projectEndDate = new javax.swing.JLabel();
    projectDuration = new javax.swing.JLabel();
    projectState = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem7 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));

    jPanel5.setBackground(new java.awt.Color(255, 255, 255));
    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Docente que me asesora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14))); // NOI18N

    projectTeacherAddress.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
    projectTeacherAddress.setText("Dirección del profesor");

    projectTeacherName.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
    projectTeacherName.setText("Nombre del profesor");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(projectTeacherName, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addComponent(projectTeacherAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addComponent(projectTeacherName)
        .addGap(18, 18, 18)
        .addComponent(projectTeacherAddress)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel9.setBackground(new java.awt.Color(255, 255, 255));
    jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Docente titular del tribunal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14))); // NOI18N

    tribunalTeacherName.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
    tribunalTeacherName.setText("Nombre del docente");

    tribunalTeacherAddress.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
    tribunalTeacherAddress.setText("Dirección del docente");

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
      jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel9Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(tribunalTeacherAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel9Layout.createSequentialGroup()
            .addComponent(tribunalTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 53, Short.MAX_VALUE))))
    );
    jPanel9Layout.setVerticalGroup(
      jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel9Layout.createSequentialGroup()
        .addComponent(tribunalTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(12, 12, 12)
        .addComponent(tribunalTeacherAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel4.setBackground(new java.awt.Color(255, 255, 255));
    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tribunal que lo evalua"));

    tribunalPresentationPlace.setText("Lugar de presentación");

    tribunalComponentsNumber.setText("Número de integrantes");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(tribunalPresentationPlace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(tribunalComponentsNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addComponent(tribunalPresentationPlace)
        .addGap(18, 18, 18)
        .addComponent(tribunalComponentsNumber)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    studentNames.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
    studentNames.setText("Nombres del estudiante");

    studentCode.setText("Código del estudiante");

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del proyecto"));

    projectTheme.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
    projectTheme.setText("Tema del proyecto");

    projectStartDate.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
    projectStartDate.setText("Fecha de inicio");

    projectEndDate.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
    projectEndDate.setText("Fecha de terminación");

    projectDuration.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
    projectDuration.setText("Duracion");

    projectState.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
    projectState.setText("Estado");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 346, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addContainerGap()
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projectStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(projectDuration)
                .addComponent(projectState)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(projectEndDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(projectTheme, javax.swing.GroupLayout.Alignment.LEADING)))
              .addContainerGap(174, Short.MAX_VALUE)))))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 183, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(projectTheme)
          .addGap(18, 18, 18)
          .addComponent(projectStartDate)
          .addGap(18, 18, 18)
          .addComponent(projectEndDate)
          .addGap(18, 18, 18)
          .addComponent(projectDuration)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
          .addComponent(projectState)
          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    jMenu1.setText("Archivo");

    jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrar_16px.png"))); // NOI18N
    jMenuItem7.setText("Cerrar");
    jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem7ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem7);

    jMenuBar1.add(jMenu1);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(studentNames)
          .addComponent(studentCode)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(studentNames)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(studentCode)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
    dispose();
    this.parent.setEnabled(true);
  }//GEN-LAST:event_jMenuItem7ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JLabel projectDuration;
  private javax.swing.JLabel projectEndDate;
  private javax.swing.JLabel projectStartDate;
  private javax.swing.JLabel projectState;
  private javax.swing.JLabel projectTeacherAddress;
  private javax.swing.JLabel projectTeacherName;
  private javax.swing.JLabel projectTheme;
  private javax.swing.JLabel studentCode;
  private javax.swing.JLabel studentNames;
  private javax.swing.JLabel tribunalComponentsNumber;
  private javax.swing.JLabel tribunalPresentationPlace;
  private javax.swing.JLabel tribunalTeacherAddress;
  private javax.swing.JLabel tribunalTeacherName;
  // End of variables declaration//GEN-END:variables
}
