package views.tribunals;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import models.Teacher;
import models.Tribunal;
import resources.Util;

/**
 *
 * @author Jhonathan Mejia Leon
 */
public class NewTribunal extends javax.swing.JFrame {
  private Tribunal tribunal;
  private javax.swing.JFrame parent;
  
  /**
   * Creates new form ReporteEstudiantes
   * @param parent
   * @param tribunalId
   */
  public NewTribunal(javax.swing.JFrame parent, int tribunalId) {
    this.parent = parent;
    this.tribunal = Tribunal.find(tribunalId);
    
    initComponents();
    addAttributes();
    loadData();
    try {
      loadTeachers();
    } catch(SQLException e) {
      System.out.printf("Error por: %s", e.getMessage());
    }
  }
  
  private void loadData() {
    if (this.tribunal == null) return;
    this.testPlace.setText(this.tribunal.getTestPlace());
    this.componentsNumber.setText(String.valueOf(this.tribunal.getComponentsNumber()));
    this.titularTeacherLabel.setText("Profesor titular: " + this.tribunal.getTitularTeacher().getFullName());
  }
  
  private void loadTeachers() throws SQLException {
    Teacher.all().forEach(teacher -> {
      this.teachersCombo.addItem(String.format("%d- %s", teacher.getId(), teacher.getFullName()));
    });
  }
  
  private void addAttributes() {
    setLocationRelativeTo(this.parent);
    setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    this.addWindowListener(new WindowListener() {
      @Override
      public void windowOpened(WindowEvent e) {
        parent.setEnabled(false);
      }

      @Override
      public void windowClosing(WindowEvent e) {
        parent.setEnabled(true);
      }

      @Override
      public void windowClosed(WindowEvent e) {}

      @Override
      public void windowIconified(WindowEvent e) {}

      @Override
      public void windowDeiconified(WindowEvent e) {}

      @Override
      public void windowActivated(WindowEvent e) {}

      @Override
      public void windowDeactivated(WindowEvent e) {}
    });
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel9 = new javax.swing.JPanel();
    testPlace = new javax.swing.JTextField();
    titularTeacherLabel = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jButton2 = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    componentsNumber = new javax.swing.JFormattedTextField(new Integer(1));
    teachersCombo = new javax.swing.JComboBox<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información-Nuevo Tribunal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 12), new java.awt.Color(0, 102, 255))); // NOI18N

    titularTeacherLabel.setText("Profesor titular");

    jLabel3.setText("Lugar de Presentación");

    jButton2.setText("Guardar");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jLabel4.setText("Número de componentes");

    teachersCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un profesor" }));

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
      jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(testPlace)
      .addGroup(jPanel9Layout.createSequentialGroup()
        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3)
          .addComponent(titularTeacherLabel)
          .addComponent(jLabel4))
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(teachersCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 346, Short.MAX_VALUE)
          .addComponent(componentsNumber, javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jButton2)))
        .addContainerGap())
    );
    jPanel9Layout.setVerticalGroup(
      jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel9Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(testPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(titularTeacherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(teachersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(componentsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jButton2)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if (this.teachersCombo.getSelectedIndex() == 0 && this.tribunal == null) {
      Util.showWarning(this, "Selecciona un profesor válido");
      return;
    }
    String testPlaceS = this.testPlace.getText();
    int componentsNumberS = Integer.parseInt(this.componentsNumber.getValue().toString());
    int teacherId = 0;
    
    if (this.teachersCombo.getSelectedIndex() != 0)
      teacherId = Util.getPKFromCombo(this.teachersCombo);
    
    if (this.tribunal != null)
      teacherId = this.tribunal.getTitularTeacherId();
    
    if (!Util.hasText(testPlaceS) || !Util.hasText(String.valueOf(teacherId)) || componentsNumberS == 0) {
      Util.showWarning(this, "Los datos no son válidos");
      return;
    }
    if (this.tribunal == null) {
      this.tribunal = new Tribunal(0, testPlaceS, componentsNumberS, teacherId);
      try {
        this.tribunal.save();
      } catch(SQLException e) {
        Util.showWarning(this, String.format("No se pudo guardar por: %s", e.getMessage()));
      }
    } else {
      if (!this.tribunal.getTestPlace().equals(testPlaceS)) this.tribunal.setTestPlace(testPlaceS);
      if (this.tribunal.getComponentsNumber() != componentsNumberS) this.tribunal.setComponentsNumber(componentsNumberS);
      if (teacherId != 0 && this.tribunal.getTitularTeacherId() != teacherId) this.tribunal.setTitularTeacherId(teacherId);
      
      try {
        this.tribunal.update();
      } catch(SQLException e) {
        Util.showWarning(this, String.format("No se pudo actualizar por: %s", e.getMessage()));
      }
    }
    dispose();
    parent.setEnabled(true);
    
  }//GEN-LAST:event_jButton2ActionPerformed
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JFormattedTextField componentsNumber;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JComboBox<String> teachersCombo;
  private javax.swing.JTextField testPlace;
  private javax.swing.JLabel titularTeacherLabel;
  // End of variables declaration//GEN-END:variables
}
