package views.teachers;

import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import models.Group;
import models.Student;
import models.Teacher;
import models.Tribunal;
import models.User;
import resources.TableData;
import resources.Util;
import views.groups.NewGroup;
import views.groups.ShowGroup;
import views.students.ShowStudent;
import views.tribunals.NewTribunal;
import views.tribunals.ShowTribunal;

/**
 *
 * @author Mejia & Riveros Corp.
 */
public class ViewTeacher extends javax.swing.JFrame {
  private User user;
  private Teacher teacher;
  
  //Sorters
  private TableRowSorter studentsSorter;
  private TableRowSorter projectsSorter;
  private TableRowSorter tribunalsSorter;
  private TableRowSorter groupsSorter;
  
  /**
   * Creates new form Ventana
   * @param user
   */
  public ViewTeacher(User user) {
    this.user = user;
    this.teacher = Teacher.find(this.user.getRoleReference());
    initComponents();
    configWindow();
    addMyData();
    addSorters();
    try {
      loadData();
    } catch(NullPointerException | SQLException e) {
      System.out.println(e.getMessage());
    }
  }

  private void configWindow() {
    setLocationRelativeTo(null);
    setTitle(String.format("Usted se ha identificado como: %s - Profesor", this.user.getUsername()));
    String text = "Escriba aquí para buscar";
    Util.addPlaceholder(studentsField, text);
    Util.addPlaceholder(groupsField, text);
    Util.addPlaceholder(tribunalsField, text);
  }
  
  private void addMyData() {
    this.idField.setText(String.valueOf(this.teacher.getId()));
    this.namesField.setText(this.teacher.getName());
    this.lastNamesField.setText(this.teacher.getLastName());
    this.addressField.setText(this.teacher.getAddress());
  }
  
  private void loadData() throws SQLException, NullPointerException {
    loadStudents();
    loadTribunals();
    loadGroups();
  }
  
  private void loadStudents() throws SQLException {
    TableData.loadStudents(studentsTable, this.teacher.getStudentsIHelp());
  }
  
  private void loadTribunals() throws SQLException {
    TableData.loadTribunals(tribunalsTable, this.teacher.getTribunalsWhereIAmMember());
  }
  
  private void loadGroups() throws SQLException {
    TableData.loadGroups(groupsTable, this.teacher.getGroupsWhereIAmMember());
  }
  
  private void addSorters() {
    studentsSorter = new TableRowSorter(studentsTable.getModel());
    studentsTable.setRowSorter(studentsSorter);
    
    tribunalsSorter = new TableRowSorter(tribunalsTable.getModel());
    tribunalsTable.setRowSorter(tribunalsSorter);
    
    groupsSorter = new TableRowSorter(groupsTable.getModel());
    groupsTable.setRowSorter(groupsSorter);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane2 = new javax.swing.JTabbedPane();
    jPanel2 = new javax.swing.JPanel();
    searchStudentsBy = new javax.swing.JComboBox();
    studentsField = new javax.swing.JTextField();
    jButton5 = new javax.swing.JButton();
    viewStudent = new javax.swing.JButton();
    jScrollPane7 = new javax.swing.JScrollPane();
    studentsTable = new javax.swing.JTable();
    jPanel5 = new javax.swing.JPanel();
    tribunalsField = new javax.swing.JTextField();
    modifyTribunal = new javax.swing.JButton();
    searchTribunalsBy = new javax.swing.JComboBox();
    jButton19 = new javax.swing.JButton();
    viewTribunal = new javax.swing.JButton();
    jScrollPane5 = new javax.swing.JScrollPane();
    tribunalsTable = new javax.swing.JTable();
    jPanel3 = new javax.swing.JPanel();
    searchGroupsBy = new javax.swing.JComboBox();
    groupsField = new javax.swing.JTextField();
    modifyGroup = new javax.swing.JButton();
    jButton11 = new javax.swing.JButton();
    viewGroup = new javax.swing.JButton();
    jScrollPane6 = new javax.swing.JScrollPane();
    groupsTable = new javax.swing.JTable();
    jPanel1 = new javax.swing.JPanel();
    jPanel6 = new javax.swing.JPanel();
    idField = new javax.swing.JTextField();
    namesField = new javax.swing.JTextField();
    lastNamesField = new javax.swing.JTextField();
    addressField = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jLabel6 = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem7 = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenuItem4 = new javax.swing.JMenuItem();
    jMenuItem5 = new javax.swing.JMenuItem();
    jMenuItem6 = new javax.swing.JMenuItem();
    jMenu3 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    searchStudentsBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar por:", "Numero de Registro", "Codigo", "Nombre", "Apellido" }));

    studentsField.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        studentsFieldKeyPressed(evt);
      }
    });

    jButton5.setText("Refresh");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton5ActionPerformed(evt);
      }
    });

    viewStudent.setText("Ver");
    viewStudent.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        viewStudentActionPerformed(evt);
      }
    });

    studentsTable.setBorder(null);
    studentsTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Número de registro", "CI", "Nombres", "Apellidos"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane7.setViewportView(studentsTable);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(searchStudentsBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(studentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
        .addComponent(viewStudent)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButton5)
        .addContainerGap())
      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
          .addGap(11, 11, 11)
          .addComponent(jScrollPane7)
          .addGap(11, 11, 11)))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(searchStudentsBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(studentsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton5)
          .addComponent(viewStudent))
        .addContainerGap(368, Short.MAX_VALUE))
      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
          .addGap(43, 43, 43)
          .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
          .addContainerGap()))
    );

    jTabbedPane2.addTab("Estudiantes", jPanel2);

    tribunalsField.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        tribunalsFieldKeyPressed(evt);
      }
    });

    modifyTribunal.setText("Modificar");
    modifyTribunal.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        modifyTribunalActionPerformed(evt);
      }
    });

    searchTribunalsBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar por:", "Id", "Lugar de Presentación" }));

    jButton19.setText("Refresh");
    jButton19.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton19ActionPerformed(evt);
      }
    });

    viewTribunal.setText("Ver");
    viewTribunal.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        viewTribunalActionPerformed(evt);
      }
    });

    tribunalsTable.setBorder(null);
    tribunalsTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "ID", "Lugar de presentación", "Número de componentes", "ID Titular", "Nombres titular"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane5.setViewportView(tribunalsTable);

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(searchTribunalsBy, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(tribunalsField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
        .addComponent(modifyTribunal)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(viewTribunal)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButton19)
        .addContainerGap())
      .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
          .addGap(11, 11, 11)
          .addComponent(jScrollPane5)
          .addGap(11, 11, 11)))
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(modifyTribunal)
          .addComponent(searchTribunalsBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tribunalsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton19)
          .addComponent(viewTribunal))
        .addContainerGap(368, Short.MAX_VALUE))
      .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
          .addGap(43, 43, 43)
          .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
          .addContainerGap()))
    );

    jTabbedPane2.addTab("Tribunal", jPanel5);

    searchGroupsBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar por:", "ID", "Nombre" }));

    groupsField.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        groupsFieldKeyPressed(evt);
      }
    });

    modifyGroup.setText("Modificar");
    modifyGroup.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        modifyGroupActionPerformed(evt);
      }
    });

    jButton11.setText("Refresh");
    jButton11.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton11ActionPerformed(evt);
      }
    });

    viewGroup.setText("Ver");
    viewGroup.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        viewGroupActionPerformed(evt);
      }
    });

    groupsTable.setBorder(null);
    groupsTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "ID", "Nombre", "Número de componentes", "ID Titular", "Nombres titular"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane6.setViewportView(groupsTable);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(searchGroupsBy, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(groupsField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
        .addComponent(modifyGroup)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(viewGroup)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButton11)
        .addContainerGap())
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
          .addGap(11, 11, 11)
          .addComponent(jScrollPane6)
          .addGap(11, 11, 11)))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(modifyGroup)
          .addComponent(searchGroupsBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(groupsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton11)
          .addComponent(viewGroup))
        .addContainerGap(368, Short.MAX_VALUE))
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
          .addGap(43, 43, 43)
          .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
          .addContainerGap()))
    );

    jTabbedPane2.addTab("Grupos", jPanel3);

    jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información Personal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 12), new java.awt.Color(0, 102, 255))); // NOI18N

    idField.setEditable(false);

    jLabel2.setText("Identificación:");

    jLabel3.setText("Nombres:");

    jLabel4.setText("Apellidos:");

    jLabel5.setText("Dirección:");

    jButton1.setText("Modificar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel6Layout.createSequentialGroup()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel4)
              .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(addressField)
          .addComponent(idField)
          .addGroup(jPanel6Layout.createSequentialGroup()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
            .addGap(0, 313, Short.MAX_VALUE))
          .addComponent(namesField)
          .addComponent(lastNamesField, javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jButton1)))
        .addContainerGap())
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(namesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lastNamesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButton1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Profesor.png"))); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
          .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    jTabbedPane2.addTab("Mis Datos", jPanel1);

    jMenu1.setText("Archivo");

    jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrar_16px.png"))); // NOI18N
    jMenuItem7.setText("Cerrar Sesión");
    jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem7ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem7);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Ver");

    jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
    jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil-ruler-icon.png"))); // NOI18N
    jMenuItem3.setText("Reporte de Proyectos");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem3ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem3);

    jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK));
    jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/igroup_n.png"))); // NOI18N
    jMenuItem4.setText("Reporte de Grupos");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem4ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem4);

    jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
    jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
    jMenuItem5.setText("Reporte de Profesores");
    jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem5ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem5);

    jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
    jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Graduate-male-icon.png"))); // NOI18N
    jMenuItem6.setText("Reporte de Estudiantes");
    jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem6ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem6);

    jMenuBar1.add(jMenu2);

    jMenu3.setText("Ayuda");

    jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
    jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ayuda_16px.png"))); // NOI18N
    jMenuItem1.setText("Índice");
    jMenu3.add(jMenuItem1);

    jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/acercaDe_16px.png"))); // NOI18N
    jMenuItem2.setText("Acerca de");
    jMenu3.add(jMenuItem2);

    jMenuBar1.add(jMenu3);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jTabbedPane2)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 6, Short.MAX_VALUE)
        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
    dispose();
    new views.users.Login().setVisible(true);
  }//GEN-LAST:event_jMenuItem7ActionPerformed

  private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    new views.projects.ReporteProyectos(this).setVisible(true);
  }//GEN-LAST:event_jMenuItem3ActionPerformed

  private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    new views.groups.ReporteGrupo(this).setVisible(true);
  }//GEN-LAST:event_jMenuItem4ActionPerformed

  private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
    new views.students.ReporteEstudiantes(this).setVisible(true);
  }//GEN-LAST:event_jMenuItem5ActionPerformed

  private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    new views.teachers.ReporteProfesores(this).setVisible(true);
  }//GEN-LAST:event_jMenuItem6ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    try {
      loadStudents();
    } catch (SQLException ex) {
      System.out.println(ex.getMessage());
    }
  }//GEN-LAST:event_jButton5ActionPerformed

  private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
    try {
      loadTribunals();
    } catch (SQLException ex) {
      System.out.println(ex.getMessage());
    }
  }//GEN-LAST:event_jButton19ActionPerformed

  private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    try {
      loadGroups();
    } catch (SQLException ex) {
      System.out.println(ex.getMessage());
    }
  }//GEN-LAST:event_jButton11ActionPerformed

  private void studentsFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentsFieldKeyPressed
    if(searchStudentsBy.getSelectedIndex() == 0 || studentsTable.getRowCount() <= 0) return;
    studentsSorter.setRowFilter(RowFilter.regexFilter(studentsField.getText(), searchStudentsBy.getSelectedIndex()-1));
  }//GEN-LAST:event_studentsFieldKeyPressed

  private void tribunalsFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tribunalsFieldKeyPressed
    if(searchTribunalsBy.getSelectedIndex() == 0 || tribunalsTable.getRowCount() <= 0) return;
    tribunalsSorter.setRowFilter(RowFilter.regexFilter(tribunalsField.getText(), searchTribunalsBy.getSelectedIndex()-1));
  }//GEN-LAST:event_tribunalsFieldKeyPressed

  private void groupsFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_groupsFieldKeyPressed
    if(searchGroupsBy.getSelectedIndex() == 0 || groupsTable.getRowCount() <= 0) return;
    groupsSorter.setRowFilter(RowFilter.regexFilter(groupsField.getText(), searchGroupsBy.getSelectedIndex()-1));
  }//GEN-LAST:event_groupsFieldKeyPressed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String name = this.namesField.getText();
    String lastName = this.lastNamesField.getText();
    String address = this.addressField.getText();

    if (!Util.hasText(address) || !Util.hasText(name) || !Util.hasText(lastName)) {
      JOptionPane.showMessageDialog(this, "Debes llenar todos los campos", "Rellena los campos", JOptionPane.ERROR_MESSAGE);
      return;
    }
    if (!address.equals(this.teacher.getAddress())) this.teacher.setAddress(address);
    if (!name.equals(this.teacher.getName())) this.teacher.setName(name);
    if (!lastName.equals(this.teacher.getLastName())) this.teacher.setLastName(lastName);
    try {
      this.teacher.update();
      JOptionPane.showMessageDialog(this.jPanel6, "Datos guardados", "OK", JOptionPane.INFORMATION_MESSAGE);
    } catch(SQLException e) {
      JOptionPane.showMessageDialog(this, String.format("No se ha podido actualizar por: %s", e.getMessage()), "Error", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  private void modifyTribunalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyTribunalActionPerformed
    int tribunalId;
    try {
      tribunalId = getPK(tribunalsTable);
    } catch(Exception e) {
      Util.showWarning(this, e.getMessage());
      return;
    }
    new NewTribunal(this, tribunalId).setVisible(true);
  }//GEN-LAST:event_modifyTribunalActionPerformed

  private void modifyGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyGroupActionPerformed
    int groupId;
    try {
      groupId = getPK(groupsTable);
    } catch(Exception e) {
      Util.showWarning(this, e.getMessage());
      return;
    }
    new NewGroup(this, groupId).setVisible(true);
  }//GEN-LAST:event_modifyGroupActionPerformed

  private void viewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentActionPerformed
    int studentId;
    try {
      studentId = getPK(studentsTable);
    } catch(Exception e) {
      Util.showWarning(this, e.getMessage());
      return;
    }
    new ShowStudent(this, Student.find(studentId)).setVisible(true);
  }//GEN-LAST:event_viewStudentActionPerformed

  private void viewTribunalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTribunalActionPerformed
    int tribunalId;
    try {
      tribunalId = getPK(tribunalsTable);
    } catch(Exception e) {
      Util.showWarning(this, e.getMessage());
      return;
    }
    new ShowTribunal(this, Tribunal.find(tribunalId)).setVisible(true);
  }//GEN-LAST:event_viewTribunalActionPerformed

  private void viewGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGroupActionPerformed
    int groupId;
    try {
      groupId = getPK(groupsTable);
    } catch(Exception e) {
      Util.showWarning(this, "Debes seleccionar una fila");
      return;
    }
    new ShowGroup(this, Group.find(groupId)).setVisible(true);
  }//GEN-LAST:event_viewGroupActionPerformed
  
  private int getPK(javax.swing.JTable table) throws ArrayIndexOutOfBoundsException, IndexOutOfBoundsException {
    return Integer.parseInt(table.getValueAt(table.getSelectedRow(), 0).toString());
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField addressField;
  private javax.swing.JTextField groupsField;
  private javax.swing.JTable groupsTable;
  private javax.swing.JTextField idField;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton11;
  private javax.swing.JButton jButton19;
  private javax.swing.JButton jButton5;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenu jMenu3;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JMenuItem jMenuItem4;
  private javax.swing.JMenuItem jMenuItem5;
  private javax.swing.JMenuItem jMenuItem6;
  private javax.swing.JMenuItem jMenuItem7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JScrollPane jScrollPane5;
  private javax.swing.JScrollPane jScrollPane6;
  private javax.swing.JScrollPane jScrollPane7;
  private javax.swing.JTabbedPane jTabbedPane2;
  private javax.swing.JTextField lastNamesField;
  private javax.swing.JButton modifyGroup;
  private javax.swing.JButton modifyTribunal;
  private javax.swing.JTextField namesField;
  private javax.swing.JComboBox searchGroupsBy;
  private javax.swing.JComboBox searchStudentsBy;
  private javax.swing.JComboBox searchTribunalsBy;
  private javax.swing.JTextField studentsField;
  private javax.swing.JTable studentsTable;
  private javax.swing.JTextField tribunalsField;
  private javax.swing.JTable tribunalsTable;
  private javax.swing.JButton viewGroup;
  private javax.swing.JButton viewStudent;
  private javax.swing.JButton viewTribunal;
  // End of variables declaration//GEN-END:variables
}
